<?php
/**
 * @file
 * Protected Pages install file.
 */

/**
 * Implements hook_schema().
 */
function protected_pages_schema() {
  $schema['protected_pages'] = array(
    'fields' => array(
      'pid' => array(
        'description' => 'The primary key is always unique.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'password' => array(
        'type' => 'varchar',
        'description' => 'The password of the protected page.',
        'length' => '128',
        'not null' => TRUE,
      ),
      'path' => array(
        'type' => 'varchar',
        'description' => 'The path of the protected page.',
        'length' => '255',
        'not null' => TRUE,
      ),
    ),
    'indexes' => array(
      'path' => array('path'),
    ),
    'primary key' => array('pid'),
  );

  return $schema;
}

/**
 * Implements hook_enable().
 */
function protected_pages_enable() {
  backdrop_set_message(t('The Protected Pages module has been successfully enabled.
    Visit the <a href="@permissions">permissions</a>, and set the permissions.',
    array('@permissions' => url('admin/people/permissions', array('fragment' => 'module-protected_pages')))));
}

/**
 * Adds new values to protected pages configuration.
 */
function protected_pages_update_1001(&$sandbox) {
  config_set('protected_pages.settings', 'protected_pages_flood_limit', '50');
  config_set('protected_pages.settings', 'protected_pages_flood_window', '3600');

  return t('Added Protected Pages settings for flood control.');
}
